 # <span style="color:red"><center>__Introducción Tensores Juan David Marín__</center></span>

In [1]:
import tensorflow as tf
import numpy as np

## Esenciales

In [6]:
t0 = tf.constant(4)
print(t0)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
t = tf.constant([1,5])
print(t)

tf.Tensor([1 5], shape=(2,), dtype=int32)


In [7]:
t1 = tf.constant([1,3,4])
print(t1)

tf.Tensor([1 3 4], shape=(3,), dtype=int32)


In [10]:
t23 = tf.constant([[1,2,3],[4,5,6]])
print(t23)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [13]:
t235 = tf.constant([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],
                  [[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]]])
print(t235)

tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]], shape=(2, 3, 5), dtype=int32)


In [15]:
t235.numpy()

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [16]:
t235.numpy().shape

(2, 3, 5)

In [17]:
t235.shape

TensorShape([2, 3, 5])

## <span style="color:green">_Algebra mínima de tensores_</span>

In [23]:
A = tf.constant([[1,2],[3,4]])
B = tf.constant([[5,6],[7,8]])
print(A, '\n')
print(B, '\n')
print(tf.add(A,B), '\n') # Suma las listas
print(tf.multiply(A,B), '\n')
print(tf.matmul(A,B),'\n')

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



In [27]:
print(A+B,'\n')
print(A*B,'\n')
print(A@B, '\n')

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



## <span style="color:green">_Funciones de Reducción_</span>

In [42]:
c = tf.constant([[4.0,5.0],[10.0,1.0]])

print(c,'\n')
print(tf.reduce_max(c),'\n')
print(tf.reduce_min(c),'\n')
print(tf.reduce_mean(c), '\n')
print(tf.argmax(c),'\n') # ubica el elemento maximo 
print(tf.nn.softmax(c),'\n')
print(tf.reduce_sum(tf.nn.softmax(c), axis = 1))

tf.Tensor(
[[ 4.  5.]
 [10.  1.]], shape=(2, 2), dtype=float32) 

tf.Tensor(10.0, shape=(), dtype=float32) 

tf.Tensor(1.0, shape=(), dtype=float32) 

tf.Tensor(5.0, shape=(), dtype=float32) 

tf.Tensor([1 0], shape=(2,), dtype=int64) 

tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32) 

tf.Tensor([1. 1.], shape=(2,), dtype=float32)



## <span style="color:green">_Tipo, forma y dimensión_</span>

In [52]:
t = tf.constant([
    [[0,1,2,3,4],
     [5,6,7,8,9]],
    [[10,11,12,13,14],
    [15,16,17,18,19]],
    [[20,21,22,23,24],
    [25,26,27,28,29]]
])

print(t,'\n')
print(t.dtype,'\n')
print(t.shape,'\n')
print(t.ndim,'\n')
print(t.shape[2],'\n')
print(tf.size(t.numpy()))


tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32) 

<dtype: 'int32'> 

(3, 2, 5) 

3 

5 

tf.Tensor(30, shape=(), dtype=int32)



## <span style="color:green">_Indexación_</span>

### <span style="color:blue">_Indexación en un solo eje_</span>

 * Los índices empiezan en cero.
 * Los índices negativos cuentan hacia atrás desde el final.
 * Los dos puntos (:) se utilizan para los cortes. inicio:final:salto



In [59]:
t1 = tf.constant([0,1,1,2,3,5,8,13,21,34])
print('Primer número:', t1[0])
print('Segundo número:', t1[1])
print('Sexto número:', t1[6])
print('Ultimo:', t1[-1].numpy())

Primer número: tf.Tensor(0, shape=(), dtype=int32)
Segundo número: tf.Tensor(1, shape=(), dtype=int32)
Sexto número: tf.Tensor(8, shape=(), dtype=int32)
Ultimo: 34


### <span style="color:blue">_Extracción de parte de un tensor: slices_</span>


In [71]:
print('Todo', t1[:].numpy())
print('Antes de la posición 4', t1[:4].numpy())
print('Desde la posición 4 hasta el final', t1[4:].numpy())
print('Desde la posición 2 hasta la 7:', t1[1:7].numpy())
print('Todos los elementos en posición par', t1[::2].numpy())
print('Invertir todo el orden', t1[::-1].numpy())

Todo [ 0  1  1  2  3  5  8 13 21 34]
Antes de la posición 4 [0 1 1 2]
Desde la posición 4 hasta el final [ 3  5  8 13 21 34]
Desde la posición 2 hasta la 7: [1 1 2 3 5 8]
Todos los elementos en posición par [ 0  1  3  8 21]
Invertir todo el orden [34 21 13  8  5  3  2  1  1  0]


### <span style="color:blue">_Indexación multi-eje_</span>


In [73]:
t23 = tf.constant([[1,2,3],[4,5,6]])
print(t23,'\n')
print(t23.numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 

[[1 2 3]
 [4 5 6]]


print('Posición 1,1:', t23[1,1].numpy())
print('Segunda fila:', t23[1,:].numpy())
print('Segunda columna:', t23[:,1].numpy())
print('Última columna:', t23[:,-1].numpy())
print('Primer elemento de la última columna:',t23[0,-1].numpy())
print('Saltarse la primera columna: \n',t23[:,1:].numpy())

In [113]:
t = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],]) 
print(t.numpy())

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [126]:
print('Extrae la primera capa\n', t[0,:,:].numpy())
print('Extrae la primera capa\n', t[0].numpy())
print('Extrae la segunda capa\n', t[0].numpy())

Extrae la primera capa
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Extrae la primera capa
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Extrae la segunda capa
 [[0 1 2 3 4]
 [5 6 7 8 9]]


### <span style="color:blue">_Manipular formas_</span>


In [130]:
x = tf.constant([[1],[2],[3]])
print(x.numpy(),'\n')
print(x.shape,'\n')
print(x.shape.as_list())

[[1]
 [2]
 [3]] 

(3, 1) 

[3, 1]


In [136]:
reshape = tf.reshape(x,[1,3])
print(reshape.numpy())
print(x.numpy())

[[1 2 3]]
[[1]
 [2]
 [3]]


In [158]:
print(t.numpy(),'\n')
print(tf.reshape(t,[1,30]).numpy())

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29]]


# Aplana un tensor

 * <span style="color:blue">Esta operación permite ver el orden como están organizados los datos en memoria</span>
 


In [165]:
print('tensor actual: \n', t.numpy())

flat = tf.reshape(t,[-1])
print('\nTensor aplanado:', flat.numpy())

tensor actual: 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]

Tensor aplanado: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [166]:
print(t.shape.as_list())

[3, 2, 5]


In [175]:
print(tf.reshape(t,[5*2,3]))
print('\n',tf.reshape(t,[2*3,5]))


tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]], shape=(10, 3), dtype=int32)

 tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [176]:
print(tf.reshape(t, [2,3*5]))

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]], shape=(2, 15), dtype=int32)


In [177]:
print(tf.reshape(t, [-1,5]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [180]:
print(tf.reshape(t, [3,-1]))

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


In [181]:
print(tf.reshape(t, [3,2,5]))

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


## Definición Conversión de tipos. Cast

In [193]:
f64_tensor = tf.constant([2.0,4.0,6.0], dtype = tf.float64)
print(f64_tensor)

f16_tensor = tf.cast(f64_tensor, dtype = tf.float16)
print(f16_tensor)

u8_tensor = tf.cast(f16_tensor, dtype = tf.uint8)
print(u8_tensor)

tf.Tensor([2. 4. 6.], shape=(3,), dtype=float64)
tf.Tensor([2. 4. 6.], shape=(3,), dtype=float16)
tf.Tensor([2 4 6], shape=(3,), dtype=uint8)


In [ ]:

f64_tensor = tf.constant([2.0, 4.0, 6.0], dtype = tf.float64)
print(f64_tensor)

f16_tensor = tf.cast(f64_tensor,dtype= tf.float16)
print(f16_tensor)

u8_tensor = tf.cast(f16_tensor, dtype = tf.uint8)
print(u8_tensor)

# Radiofusión (broadcasting)

In [198]:
x = tf.constant([1,2,3])
y = tf.constant(2)
z = tf.constant([2,2,2])

# el mismo resultado

print(tf.multiply(x,2))
print(x*y)
print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [207]:
x = tf.reshape(x,[3,1])
y = tf.range(1,5)
print(x.numpy(), "\n")
print(y.numpy(), "\n")
print(x, "\n")
print(y, "\n")

[[1]
 [2]
 [3]] 

[1 2 3 4] 

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 



In [208]:
print(tf.multiply(x,y))

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


# tf.broadcast_to

In [213]:
print(tf.broadcast_to([1,2,3], [3,3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


# tf.convert_to_tensor

# Tensores irregulares (ragged tensors) 

In [215]:
regged_list = [
    [0,1,2,3],
    [4,5],
    [6,7,8],
    [9]
]

In [219]:
try:
    tensor = tf.constant(ragged_list)
except Exception as e:
    print(f'{type(e).__name__}: {e}')

NameError: name 'ragged_list' is not defined


In [250]:
ragged_t = tf.ragged.constant(regged_list)
print(ragged_t.shape)
print(ragged_t.numpy())

(4, None)
[array([0, 1, 2, 3]) array([4, 5]) array([6, 7, 8]) array([9])]


# Tensores de strings

In [251]:
st = tf.constant("Este tensor string")
print(st)

tf.Tensor(b'Este tensor string', shape=(), dtype=string)


In [252]:
st = tf.constant(["Este tensor string",
                 "Cadena 2",
                 "Cadena 3",
                 "🐍"])
print(st)

tf.Tensor([b'Este tensor string' b'Cadena 2' b'Cadena 3' b'\xf0\x9f\x90\x8d'], shape=(4,), dtype=string)


In [254]:
print(tf.strings.split(st))

<tf.RaggedTensor [[b'Este', b'tensor', b'string'], [b'Cadena', b'2'], [b'Cadena', b'3'], [b'\xf0\x9f\x90\x8d']]>


In [260]:
st_split = tf.strings.split(st)
for i in st_split:
    print(i)

tf.Tensor([b'Este' b'tensor' b'string'], shape=(3,), dtype=string)
tf.Tensor([b'Cadena' b'2'], shape=(2,), dtype=string)
tf.Tensor([b'Cadena' b'3'], shape=(2,), dtype=string)
tf.Tensor([b'\xf0\x9f\x90\x8d'], shape=(1,), dtype=string)


## string to number

In [264]:
st = tf.constant('1 10 10.4')
print(tf.strings.to_number(tf.strings.split(st, ' ')))

tf.Tensor([ 1.  10.  10.4], shape=(3,), dtype=float32)


# Tensores dispersos. SparseTensor

In [285]:
sparse_tensor = tf.sparse.SparseTensor(indices =[[0,1],[1,2]],
                                      values = [1,2],
                                      dense_shape = [3,4])

print(sparse_tensor)
print('\n', tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

 tf.Tensor(
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
